### ISSUE TITLE
Project with pytest and pytest-mock fails to compile scss on Heroku

### ISSUE THREAD

**Issue by tbjers** [drpancake/heroku-buildpack-django-sass#1]
Howdy,

I ran into the following problem after switching to `pytest`. Not sure how to resolve it.

Thankful for any assistance.

```
-----> heroku-buildpack-django-sass app detected
-----> $ python manage.py compilescss --traceback
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python3.7/site-packages/django/template/utils.py", line 66, in __getitem__
           return self._engines[alias]
       KeyError: 'django'
       
       During handling of the above exception, another exception occurred:
       
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python3.7/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
           module = import_module(entry[1])
         File "/app/.heroku/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
         File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
         File "<frozen importlib._bootstrap>", line 983, in _find_and_load
         File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
         File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
         File "<frozen importlib._bootstrap_external>", line 728, in exec_module
         File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
         File "/tmp/build_ea488d44_/APPNAME/templatetags/tests/test_amazon_link.py", line 3, in <module>
           from pytest_mock import MockerFixture
       ModuleNotFoundError: No module named 'pytest_mock'
```

**`Pipfile`**

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
babel = "*"
bottlenose = "*"
django = "*"
django-anymail = { extras = ["mailgun"], version = "*" }
django-compressor = "*"
django-dynamic-preferences = "*"
django-environ = "*"
django-perms-provisioner = "*"
django-sass-processor = "*"
flask-cors = "*"
gunicorn = "*"
libsass = "*"
measurement = "*"
polib = "*"
psycopg2-binary = "*"
python-dateutil = "*"
pyyaml = "*"
rollbar = "*"
sqlalchemy = "*"
timezones = "*"
whitenoise = { extras = ["brotli"], version = "*" }

[dev-packages]
black = "~=20.8b1"
coverage = { extras = ["toml"], version = "*" }
faker = "*"
install = "*"
invoke = "*"
pre-commit = "*"
pylint = "*"
pylint-django = "*"
pytest = "*"
pytest-cov = "*"
pytest-django = "*"
pytest-mock = "*"
skjold = "*"
wheel = "*"

[requires]
python_version = "3.7"

[pipenv]
allow_prereleases = true
```

**Comment by tbjers** [comment]
I have figured out the issue. I had a subdirectory called `APPNAME/templatetags/tests` that was causing this for some reason. If I move the tests from that directory to `APPNAME/tests` then `compilescss` starts working again.
